name: Build & Deploy

on:
  push:
    tags:
      - 'v*.*.*'
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.12
    steps:
      - uses: actions/checkout@master
      - name: dependencies
        run: go mod download
      - name: make test
        run: make test
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.goreleaser }}
        if: success()
        run: |
          go get github.com/goreleaser/goreleaser
          goreleaser release --skip-validate --skip-publish