name: Build & Deploy

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-beta'
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@master
      -
        name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      -
        name: dependencies
        run: |
          go mod download
      -
        name: docker login
        env:
          DOCKER_USER: ${{ secrets.docker_user }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      -
        name: build
        run: |
          export GOPATH=/home/runner/go
          export PATH="$PATH:$GOPATH/bin"
          make build
      -  
        name: test
        run: |
          export GOPATH=/home/runner/go
          export PATH="$PATH:$GOPATH/bin"
          make test
          make smoke-test
      - 
        name: release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.goreleaser }}

