name: VS Code DockerHub Build & Push

on:
  push:
    branches:
      - 'feature/update_vscode_dev_setup' # TODO: change to 'master'
    paths:
      - '.devcontainer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@master
      -
        name: docker login
        env:
          DOCKER_USER: ${{ secrets.docker_user }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      -
        name: Build & Push to DockerHub
        env:
          DOCKER_ORG: stelligent
        run: bash ./.devcontainer/build/dockerhub.sh
